(function(){
var NS="http://www.w3.org/2000/svg",stops=[],uid=0,tok=0;
function E(t,a,p){var e=document.createElementNS(NS,t);for(var k in a)e.setAttribute(k,a[k]);if(p)p.appendChild(e);return e}
function D(css,p,txt){var e=document.createElement("div");e.style.cssText=css||"";if(txt)e.textContent=txt;if(p)p.appendChild(e);return e}
function P(g,x,y){g.style.transform="translate("+x.toFixed(1)+"px,"+y.toFixed(1)+"px)"}
function cl(n,a,b){return Math.max(a,Math.min(b,n))}
function bub(p,txt,col){var g=E("g",{},p),w=txt.length*7.5+12;E("rect",{x:-w/2,y:-9,width:w,height:18,rx:9,fill:col||"#000",stroke:"#fff","stroke-width":1},g);var t=E("text",{y:4,"text-anchor":"middle","font-size":11,"font-weight":700,fill:"#fff"},g);t.textContent=txt;g.style.transition="transform 1.3s ease-in-out";return g}
function loop(fn){var id,a=performance.now(),l=a;function f(n){fn((n-a)/1000,(n-l)/1000);l=n;id=requestAnimationFrame(f)}id=requestAnimationFrame(f);stops.push(function(){cancelAnimationFrame(id)})}
function every(fn,ms){fn();var id=setInterval(fn,ms);stops.push(function(){clearInterval(id)})}
function shell(box,title,note,feed){box.innerHTML="";var h=D("display:flex;justify-content:space-between;align-items:center;gap:8px;margin-bottom:8px",box);D("font-weight:700",h,title);var pill=D("font-size:12px;padding:2px 8px;border-radius:8px;background:#F9CD54;color:#3A2600;font-weight:600;flex:none",h,feed?"Connexion au flux…":"Données simulées");var s=E("svg",{viewBox:"0 0 380 240",role:"img","aria-label":title});s.style.cssText="width:100%;height:auto;display:block";box.appendChild(s);var i=D("margin-top:8px;font-weight:600",box),l=D("margin-top:6px;font-size:14px;color:var(--mut)",box);if(note)D("margin-top:6px;font-size:12px;color:var(--mut)",box,note);return{s:s,i:i,l:l,pill:pill}}
function poll(url,u,fn){function g(){fetch(url,{cache:"no-store"}).then(function(r){return r.json()}).then(function(d){fn(d);u.pill.textContent="Flux en direct";u.pill.style.background="#48BF8A";u.pill.style.color="#000"}).catch(function(){u.pill.textContent="Flux indisponible";u.pill.style.background="#E24B4A";u.pill.style.color="#fff"})}g();var id=setInterval(g,3000);stops.push(function(){clearInterval(id)})}
var FS={FRA:[[-1,-1,.67,2,"#0055A4"],[-.33,-1,.67,2,"#fff"],[.33,-1,.67,2,"#EF4135"]],
USA:[[-1,-1,2,2,"#fff"],[-1,-1,2,.3,"#B22234"],[-1,-.4,2,.3,"#B22234"],[-1,.2,2,.3,"#B22234"],[-1,.8,2,.2,"#B22234"],[-1,-1,1,1,"#3C3B6E"]],
GBR:[[-1,-1,2,2,"#012169"],[-1,-.2,2,.4,"#fff"],[-.2,-1,.4,2,"#fff"],[-1,-.1,2,.2,"#C8102E"],[-.1,-1,.2,2,"#C8102E"]],
AUS:[[-1,-1,2,2,"#012169"],[-1,-.6,1,.2,"#C8102E"],[-.6,-1,.2,1,"#C8102E"],[.2,.2,.3,.3,"#fff"],[.5,-.5,.25,.25,"#fff"],[.4,.6,.25,.25,"#fff"]],
NZL:[[-1,-1,2,2,"#012169"],[.2,-.6,.25,.25,"#CC142B"],[.55,-.1,.25,.25,"#CC142B"],[.2,.4,.25,.25,"#CC142B"],[-.2,-.1,.25,.25,"#CC142B"]]};
function flag(p,c,r){var id="cp"+(uid++),g=E("g",{},p),cp=E("clipPath",{id:id},g);E("circle",{r:r},cp);var h=E("g",{"clip-path":"url(#"+id+")"},g);FS[c].forEach(function(q){E("rect",{x:q[0]*r,y:q[1]*r,width:q[2]*r,height:q[3]*r,fill:q[4]},h)});E("circle",{r:r,fill:"none",stroke:"#fff","stroke-width":1.5},g);return g}

function foot(box,feed,opt,rg){var u=shell(box,(rg?"Rugby":"Football")+" · positions des joueurs","Les positions viennent d'un flux de données. La radio seule ne les donne pas.",feed);var s=u.s;
E("rect",{x:4,y:4,width:372,height:232,rx:6,fill:"#0E2A1F",stroke:"#1E4D38","stroke-width":2},s);
[[190,4,190,236]].forEach(function(l){E("line",{x1:l[0],y1:l[1],x2:l[2],y2:l[3],stroke:"#2F7A58"},s)});
E("circle",{cx:190,cy:120,r:30,fill:"none",stroke:"#2F7A58"},s);E("rect",{x:4,y:60,width:50,height:120,fill:"none",stroke:"#2F7A58"},s);E("rect",{x:326,y:60,width:50,height:120,fill:"none",stroke:"#2F7A58"},s);
if(rg)[22,58,322,358].forEach(function(x){E("line",{x1:x,y1:4,x2:x,y2:236,stroke:"#2F7A58"},s)});
if(feed){var pg=E("g",{},s),m={},hb=bub(s,"A10","#000"),bg=E("g",{},s);bg.style.transition="transform 1.4s ease-in-out";E("circle",{r:5,fill:"#fff",stroke:"#000"},bg);
poll(feed,u,function(d){(d.joueurs||[]).forEach(function(j){var k=j.eq+j.num,x=4+j.x*372,y=4+j.y*232;if(!m[k]){var g=E("g",{},pg);g.style.transition="transform 1.4s ease-in-out";E("circle",{r:6,fill:j.eq=="a"?"#378ADD":"#D85A30",stroke:"#fff","stroke-width":1},g);m[k]={g:g}}m[k].x=x;m[k].y=y;P(m[k].g,x,y)});if(d.balle)P(bg,4+d.balle.x*372,4+d.balle.y*232);var a=d.acteur&&m[d.acteur.eq+d.acteur.num];if(a){var lb=d.acteur.eq.toUpperCase()+d.acteur.num;P(hb,a.x,a.y-15);hb.lastChild.textContent=lb;u.i.textContent="Joueur en action : "+lb}u.l.textContent=(d.minute?d.minute+"' ":"")+(d.score?d.score.join(" - ")+" · ":"")+(d.evenement||"")});return}
var F=rg?[[0,.06,[.5]],[1,.2,[.1,.9]],[1,.24,[.35,.65]],[1,.34,[.5]],[1,.38,[.55]],[2,.46,[.3,.5,.7]],[2,.52,[.42,.58]],[2,.58,[.3,.5,.7]]]:[[0,.04,[.5]],[1,.2,[.12,.37,.63,.88]],[2,.4,[.12,.37,.63,.88]],[3,.58,[.35,.65]]],K=[.05,.3,.45,.55],pl={a:[],b:[]};
["a","b"].forEach(function(t){F.forEach(function(r){r[2].forEach(function(v){var g=E("g",{},s);g.style.transition="transform 1.4s ease-in-out";E("circle",{r:6,fill:t=="a"?"#378ADD":"#D85A30",stroke:"#fff","stroke-width":1},g);pl[t].push({g:g,l:r[0],u:r[1],v:v})})})});
var hb=bub(s,"A10","#000"),ball=E("circle",{r:0,cx:0,cy:0},s),bg=E("g",{},s);bg.style.transition="transform 1.4s ease-in-out";E("circle",{r:5,fill:"#fff",stroke:"#000"},bg);
function lay(bx,by,poss,h){["a","b"].forEach(function(t){var d=t=="a"?1:-1;pl[t].forEach(function(p,k){var ox=t=="a"?10+p.u*360:370-p.u*360,oy=5+p.v*230,x=ox+d*(p.l?(poss==t?40:-25):0)+(bx-ox)*K[p.l],y=oy+(by-oy)*(p.l?.3:.1);if(h&&h[0]==t&&h[1]==k){x=bx-d*12;y=by+9;P(hb,cl(x,12,368),cl(y,12,228)-15);hb.lastChild.textContent=(t=="a"?"A":"B")+(k+1)}P(p.g,cl(x,12,368),cl(y,12,228))});P(bg,bx,by)})}
var S=rg?[{m:1,x:190,y:120,p:"a",h:["a",5],s:"Coup d'envoi"},{m:7,x:140,y:90,p:"b",h:["b",6],s:"Mêlée pour B"},{m:14,x:350,y:110,p:"a",h:["a",9],s:"Essai de A !"},{m:19,x:60,y:150,p:"b",h:["b",7],s:"Pénalité pour B"},{m:26,x:22,y:100,p:"b",h:["b",10],s:"Essai de B !"},{m:33,x:300,y:40,p:"a",h:["a",2],s:"Touche pour A"},{m:40,x:200,y:120,p:"a",h:["a",8],s:"Fin de la première mi-temps"}]:[{m:1,x:190,y:120,p:"a",h:["a",10],s:"Coup d'envoi"},{m:3,x:260,y:45,p:"a",h:["a",5],s:"Passe sur l'aile"},{m:6,x:150,y:150,p:"b",h:["b",6],s:"Récupération, B relance"},{m:8,x:22,y:75,p:"b",h:["b",9],s:"Tir de B, juste à côté"},{m:12,x:362,y:16,p:"a",h:["a",5],s:"Corner pour A"},{m:13,x:364,y:120,p:"a",h:["a",10],s:"But de A !"},{m:15,x:200,y:110,p:"a",h:["b",7],s:"Carton jaune pour B"},{m:17,x:100,y:130,p:"b",h:["b",10],s:"Le gardien capte"}],k=0;
every(function(){var e=S[k%S.length];k++;lay(e.x,e.y,e.p,e.h);u.i.textContent="Joueur en action : "+(e.h[0]=="a"?"A":"B")+(e.h[1]+1);u.l.textContent=e.m+"' "+e.s},2800)}

var T=[["FRA","#378ADD",1],["GBR","#D85A30",.97],["AUS","#EF9F27",1.02],["USA","#7F77DD",.99],["NZL","#1D9E75",1.01]];
function sail(box,feed){var u=shell(box,"SailGP · course","La bulle montre le drapeau de la nation de chaque équipe.",feed);var s=u.s;
E("rect",{x:4,y:4,width:372,height:232,rx:8,fill:"#0B2A3A",stroke:"#1E4D58","stroke-width":2},s);E("line",{x1:120,y1:222,x2:260,y2:222,stroke:"#8AA",["stroke-dasharray"]:"4 3"},s);E("circle",{cx:190,cy:40,r:6,fill:"#F9CD54"},s);E("circle",{cx:120,cy:222,r:5,fill:"#8AA"},s);E("circle",{cx:260,cy:222,r:5,fill:"#8AA"},s);
if(feed){var m={};poll(feed,u,function(d){var o=(d.bateaux||[]).slice().sort(function(a,b){return a.rang-b.rang});o.forEach(function(b){var k=m[b.nation];var x=4+b.x*372,y=4+b.y*232;if(!k){var col=(T.filter(function(t){return t[0]==b.nation})[0]||[0,"#fff"])[1],l=E("polyline",{fill:"none",stroke:col,"stroke-width":1.5,opacity:.6},s),g=E("g",{},s);g.style.transition="transform 1.4s linear";E("circle",{r:5,fill:col,stroke:"#fff","stroke-width":1.5},g);var f=E("g",{transform:"translate(0,-17)"},g);if(FS[b.nation])flag(f,b.nation,8);else bub(f,b.nation,"#000");k=m[b.nation]={g:g,l:l,pts:[]}}P(k.g,x,y);k.pts.push(x.toFixed(0)+","+y.toFixed(0));if(k.pts.length>50)k.pts.shift();k.l.setAttribute("points",k.pts.join(" "))});u.i.textContent="Leader : "+(o[0]?o[0].nation:"");u.l.textContent=o.map(function(b,k){return(k+1)+". "+b.nation+(b.vitesse?" "+Math.round(b.vitesse)+" km/h":"")}).join("  ·  ")});return}
var B=T.map(function(t){var l=E("polyline",{fill:"none",stroke:t[1],"stroke-width":1.5,opacity:.6},s);return{l:l,pts:[],p:0,sp:1}});
B.forEach(function(b,i){b.g=E("g",{},s);E("circle",{r:5,fill:T[i][1],stroke:"#fff","stroke-width":1.5},b.g);var f=E("g",{transform:"translate(0,-17)"},b.g);flag(f,T[i][0],8)});
function pos(p,i){var x,y;if(p<.5){var q=p/.5;y=215-175*q;x=(140+i*25)*(1-q)+190*q+20*Math.sin(q*16+i)*(1-q*.4)}else{var r=(p-.5)/.5;y=40+175*r;x=190+(i-2)*12*r+9*Math.sin(r*9+i)}return[x,y]}
var w=0;loop(function(t,dt){B.forEach(function(b,i){b.sp=T[i][2]*(1+.12*Math.sin(t*.8+i*1.7));if(b.p<1)b.p=Math.min(1,b.p+b.sp*dt*.045);var q=pos(b.p,i);b.g.setAttribute("transform","translate("+q[0].toFixed(1)+","+q[1].toFixed(1)+")");b.pts.push(q[0].toFixed(0)+","+q[1].toFixed(0));if(b.pts.length>50)b.pts.shift();b.l.setAttribute("points",b.pts.join(" "))});
var o=B.map(function(b,i){return i}).sort(function(a,b){return B[b].p-B[a].p});u.i.textContent="Leader : "+T[o[0]][0];u.l.textContent=o.map(function(i,k){return(k+1)+". "+T[i][0]+(B[i].p>=1?"":" "+Math.round(55+32*B[i].sp)+" km/h")}).join("  ·  ");
if(B.every(function(b){return b.p>=1})){w+=dt;if(w>2.5){w=0;B.forEach(function(b){b.p=0;b.pts=[]})}}})}

function golf(box,feed){var u=shell(box,"Golf · trou simulé","Le joueur en cours est indiqué au-dessus de la balle.",feed);var s=u.s;
E("rect",{x:4,y:4,width:372,height:232,rx:8,fill:"#14301F",stroke:"#1E4D38","stroke-width":2},s);E("path",{d:"M40 120 C100 80 200 80 290 100 L330 100 L330 130 C230 150 120 160 40 130 Z",fill:"#1E5C40"},s);E("ellipse",{cx:335,cy:108,rx:28,ry:22,fill:"#2F7A58"},s);E("ellipse",{cx:270,cy:152,rx:18,ry:10,fill:"#B8963C"},s);E("ellipse",{cx:180,cy:195,rx:50,ry:26,fill:"#1B4A66"},s);E("circle",{cx:40,cy:125,r:5,fill:"#ccc"},s);E("circle",{cx:342,cy:104,r:3.5,fill:"#fff"},s);
if(feed){var m={},cb=bub(s,"MAR","#000");poll(feed,u,function(d){(d.coups||[]).forEach(function(c){var b=m[c.j];if(!b){b=m[c.j]=E("g",{},s);b.style.transition="transform 1.2s ease-in-out";E("circle",{r:5,fill:"#fff",stroke:"#000","stroke-width":1.5},b)}b.x=4+c.x*372;b.y=4+c.y*232;P(b,b.x,b.y)});var cur=m[d.en_cours];if(cur){P(cb,cur.x,cur.y-16);cb.lastChild.textContent=d.en_cours}var pj=(d.joueurs||[]).filter(function(q){return q.code==d.en_cours})[0];u.i.textContent="En cours : "+(pj?pj.nom+" ("+pj.code+")":d.en_cours||"");u.l.innerHTML="";(d.joueurs||[]).forEach(function(q){D("",u.l,(q.code==d.en_cours?"▶ ":"   ")+q.code+"  "+q.nom+"  "+String(q.score).replace("-","−"))})});return}
var G=[["MAR","J. Martin","#378ADD",[[215,112],[322,104],[342,104]],-4],["DUB","L. Dubois","#D85A30",[[200,95],[325,100],[342,104]],-3],["KEL","M. Keller","#EF9F27",[[230,128],[335,112],[342,104]],-2]],tr=E("g",{},s),bl=G.map(function(g){var b=E("g",{},s);b.style.transition="transform 1.2s ease-in-out";E("circle",{r:5,fill:g[2],stroke:"#fff","stroke-width":1.5},b);P(b,40,125);return b}),cb=bub(s,"MAR","#000"),k=0,px=40,py=125;
every(function(){if(k>=11){k=0;tr.innerHTML="";bl.forEach(function(b){P(b,40,125)})}if(k>=9){k++;return}var pi=Math.floor(k/3),n=k%3,g=G[pi],e=g[3][n];if(n==0){px=40;py=125}E("line",{x1:px,y1:py,x2:e[0],y2:e[1],stroke:g[2],"stroke-width":1.5,"stroke-dasharray":"4 3"},tr);P(bl[pi],e[0],e[1]);P(cb,e[0],e[1]-16);cb.lastChild.textContent=g[0];px=e[0];py=e[1];u.i.textContent="En cours : "+g[1]+" ("+g[0]+") · coup "+(n+1)+"/3";u.l.innerHTML="";G.forEach(function(q,j){D("",u.l,(j==pi?"▶ ":"   ")+q[0]+"  "+q[1]+"  "+String(q[4]).replace("-","−"))});k++},2200)}

function tennis(box,feed){var u=shell(box,"Tennis · point en cours","Le joueur en action et celui qui sert sont indiqués en direct.",feed);var s=u.s;
E("rect",{x:4,y:4,width:372,height:232,rx:8,fill:"#1E3A5F"},s);E("rect",{x:40,y:36,width:300,height:168,fill:"#2A5B8A",stroke:"#fff","stroke-width":1.5},s);[[190,36,190,204],[115,36,115,204],[265,36,265,204],[115,120,265,120]].forEach(function(l){E("line",{x1:l[0],y1:l[1],x2:l[2],y2:l[3],stroke:"#fff","stroke-width":l[0]==190?3:1.2},s)});
var N=[["MOR","A. Moreau","#378ADD"],["KEL","B. Keller","#EF9F27"]],pl=N.map(function(n,i){var g=E("g",{},s);g.style.transition="transform .5s ease-in-out";E("circle",{r:11,fill:"none",stroke:"#fff","stroke-width":2,opacity:0},g);E("circle",{r:7,fill:n[2],stroke:"#fff","stroke-width":1.5},g);var b=E("g",{transform:"translate(0,-20)"},g);var w=48;E("rect",{x:-w/2,y:-9,width:w,height:18,rx:9,fill:"#000",stroke:"#fff"},b);var t=E("text",{y:4,"text-anchor":"middle","font-size":11,"font-weight":700,fill:"#fff"},b);t.textContent=n[0];P(g,i?356:24,120);return g}),bl=E("g",{},s);bl.style.transition="transform .55s linear";E("circle",{r:5,fill:"#F9CD54",stroke:"#000"},bl);P(bl,24,120);
if(feed){poll(feed,u,function(d){var J=d.joueurs||[];J.forEach(function(j,i){if(pl[i])pl[i].lastChild.lastChild.textContent=j.code;if(d.positions&&d.positions[i])P(pl[i],4+d.positions[i].x*372,4+d.positions[i].y*232)});if(d.balle)P(bl,4+d.balle.x*372,4+d.balle.y*232);pl.forEach(function(g,i){g.firstChild.setAttribute("opacity",i==d.en_action?1:0)});u.i.textContent="En action : "+(J[d.en_action]?J[d.en_action].nom:"")+(d.service==d.en_action?" (au service)":"");u.l.textContent=(d.score||"")+(J[d.service]?" · Au service : "+J[d.service].nom:"")});return}
var RL=[[4,0],[3,1],[5,0],[2,1],[4,0]],SC=["0-0","15-0","15-15","30-15","30-30","40-30","Jeu"],srv=0,pt=0,h=0,w=0;
every(function(){if(w>0){w--;return}var r=RL[pt];if(h>=r[0]){pt++;h=0;u.l.textContent="Point pour "+N[r[1]][1]+" · "+SC[pt];pl.forEach(function(g){g.firstChild.setAttribute("opacity",0)});w=2;if(pt>=RL.length){u.l.textContent="Jeu : "+N[0][1];pt=0;w=4}return}var ht=(srv+h)%2,ty=70+Math.random()*100,tx=ht==0?300:80;pl.forEach(function(g,i){g.firstChild.setAttribute("opacity",i==ht?1:0)});P(bl,tx,ty);P(pl[1-ht],1-ht?356:24,ty);u.i.textContent="En action : "+N[ht][1]+(h==0?" (au service)":"");h++},650)}

var DRV=[["MAR","J. Martin"],["DUB","L. Dubois"],["KEL","M. Keller"],["MOR","A. Moreau"],["ROS","G. Rossi"],["SIL","P. Silva"],["NOV","T. Novak"],["WEB","F. Weber"],["LOP","D. Lopez"],["BAU","K. Bauer"],["COS","R. Costa"],["FER","E. Ferrand"],["GIR","H. Girard"],["HAN","S. Hansen"],["IVA","V. Ivanov"],["JAN","B. Jansen"],["KLE","N. Klein"],["LAM","C. Lambert"],["MUL","O. Müller"],["NIE","I. Nielsen"],["OLS","U. Olsen"],["PET","Y. Petit"]],TC=["#E24B4A","#378ADD","#F9CD54","#1D9E75","#7F77DD","#EF9F27","#D4537E","#5DCAA5","#85B7EB","#C0DD97","#F0997B"],DD="M70 170 C40 120 80 60 150 60 C220 60 230 110 280 90 C340 70 360 130 320 175 C280 215 130 215 70 170 Z";
function f1(box,feed,opt){var u=shell(box,"Formule 1 · course",feed?"Chaque voiture porte le code à trois lettres du pilote.":"Tracé schématique, pilotes fictifs.",feed),s=u.s,my=tok;
E("rect",{x:4,y:4,width:372,height:232,rx:8,fill:"#161616",stroke:"#333","stroke-width":2},s);
fetch("circuits.json").then(function(r){return r.json()}).catch(function(){return{}}).then(function(C){if(my!==tok)return;var no=(opt||"").toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,""),k=Object.keys(C).filter(function(x){return x!="defaut"&&no.indexOf(x)>=0})[0],d=C[k]||C.defaut||DD,tk=E("path",{d:d,fill:"none",stroke:"#3A3A3A","stroke-width":14,"stroke-linejoin":"round"},s);E("path",{d:d,fill:"none",stroke:"#666","stroke-width":1,"stroke-dasharray":"5 5"},s);var L=tk.getTotalLength();
function car(code,col){var g=E("g",{},s);E("circle",{r:4.5,fill:col,stroke:"#fff"},g);var b=E("g",{transform:"translate(0,-13)"},g);E("rect",{x:-14,y:-8,width:28,height:16,rx:8,fill:col,stroke:"#fff"},b);var t=E("text",{y:3.5,"text-anchor":"middle","font-size":9.5,"font-weight":700,fill:"#000"},b);t.textContent=code;return{g:g,b:b}}
function rows(V,ld,gp){u.l.innerHTML="";V.slice(0,10).forEach(function(c,k){D("",u.l,(k+1)+". "+c.code+"  "+(c.nom||"")+(k&&gp(c)!=null?"  +"+gp(c)+" s":""))});if(V.length>10)D("color:var(--mut)",u.l,"… et "+(V.length-10)+" autres pilotes")}
if(feed){var m={};poll(feed,u,function(d){var V=(d.voitures||[]).slice().sort(function(a,b){return a.rang-b.rang});V.forEach(function(c,i){var o=m[c.code];if(!o){o=m[c.code]=car(c.code,c.couleur||"#E24B4A");o.g.style.transition="transform 2.8s linear"}o.b.setAttribute("display",i<6?"inline":"none");var q=tk.getPointAtLength((((c.p%1)+1)%1)*L);P(o.g,q.x,q.y)});u.i.textContent="Tour "+(d.tour||"")+(V[0]?" · leader : "+V[0].code+(V[0].nom?" "+V[0].nom:""):"");rows(V,0,function(c){return c.ecart})});return}
var c=DRV.map(function(x,i){var o=car(x[0],TC[i>>1]);o.p=1-i*.011;o.code=x[0];o.nom=x[1];o.sp=1-i*.002;return o});
loop(function(t,dt){c.forEach(function(q,i){q.p+=dt/18*q.sp*(1+.05*Math.sin(t*.6+i*2));var pt=tk.getPointAtLength((q.p%1)*L);q.g.setAttribute("transform","translate("+pt.x.toFixed(1)+","+pt.y.toFixed(1)+")")});var o=c.slice().sort(function(a,b){return b.p-a.p});o.forEach(function(q,k){q.b.setAttribute("display",k<6?"inline":"none")});u.i.textContent="Tour "+(Math.floor(o[0].p)+1)+" · leader : "+o[0].code+" "+o[0].nom;rows(o,0,function(q){return((o[0].p-q.p)*18).toFixed(1)})})})}

var M={Football:foot,Rugby:function(b,f,o){foot(b,f,o,1)},Voile:sail,Golf:golf,Tennis:tennis,"Formule 1":f1};
window.Scenes={start:function(sp,box,feed,opt){this.stop();var f=M[sp];if(f)f(box,feed,opt);else{box.innerHTML="";D("color:var(--mut);font-size:14px",box,"Animation bientôt disponible pour ce sport.")}},stop:function(){tok++;stops.forEach(function(f){f()});stops=[]}};
})();
